### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by 521231** [cdonohue/clean-ui#2]
Hey , when i press install it isn't working is there anything i can do  ?

**Comment by simpleidiot** [comment]
Same here. Should be fixed soon. For now download from github.

**Comment by anthonybrown** [comment]
same here, this theme won't install

**Comment by Giovanna8** [comment]
I noticed this was updated, yet GitHub is still saying it's version 1.8.2... How can one of us change this?

**Comment by cdonohue** [comment]
Since this was initially a fork from 'atom-one-dark', the release tags conflicted with the original fork. 

To remedy this, the repo had to be deleted and created again (to sever the fork relationship). 

However, once that original repo was deleted, the relationship with `apm` is gone. So, I plan on releasing this theme under a new name. 

Sorry for the long story. I'll link the new repo here as soon as it has been created.

**Comment by cdonohue** [comment]
All, thank you for your patience. Please refer to https://github.com/cdonohue/pristine-ui for further updates of this ui-theme
